### ISSUE TITLE
Question: Windows compability

### ISSUE THREAD

**Issue by Stefan-Code** [sloria/doitlive#10]
Just a quick question regarding the fix of #6 : Is this program windows compatible? I don't have a windows box to test around and the README doesn't say anything about it either.

**Comment by Stefan-Code** [comment]
@sloria I just tried the unpatched (regarding #6) version using Win 7 in a virtualbox and this happens:
Running `python3 doitlive.py play test.sh`
```
We'll do it live!
STARTING SESSION: Press Ctrl-C at any time to exit.
Traceback (most recent call last):
  File "doitlive.py", line 375, in format_prompt
    return prompt.format(**get_prompt_state())
  File "doitlive.py", line 264, in get_prompt_state
    cwd_raw = full_cwd.replace(env['HOME'], '~')
  File "C:\Users\IEUser\AppData\Local\Programs\Python\Python35-32\lib\os.py", line 681, in __getitem__
    raise KeyError(key) from None
KeyError: 'HOME'
 
During handling of the above exception, another exception occurred:
 
Traceback (most recent call last):
  File "doitlive.py", line 827, in <module>
    cli()
  File "C:\Users\IEUser\AppData\Local\Programs\Python\Python35-32\lib\site-packages\click\core.py", line 700, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\IEUser\AppData\Local\Programs\Python\Python35-32\lib\site-packages\click\core.py", line 680, in main
    rv = self.invoke(ctx)
  File "C:\Users\IEUser\AppData\Local\Programs\Python\Python35-32\lib\site-packages\click\core.py", line 1027, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\IEUser\AppData\Local\Programs\Python\Python35-32\lib\site-packages\click\core.py", line 873, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\IEUser\AppData\Local\Programs\Python\Python35-32\lib\site-packages\click\core.py", line 508, in invoke
    return callback(*args, **kwargs)
  File "doitlive.py", line 695, in play
    commentecho=commentecho)
  File "doitlive.py", line 588, in run
    magicrun(command, **state)
  File "doitlive.py", line 368, in magicrun
    magictype(text, prompt_template, speed)
  File "doitlive.py", line 353, in magictype
    echo_prompt(prompt_template)
  File "doitlive.py", line 386, in echo_prompt
    prompt = make_prompt_formatter(template)()
  File "doitlive.py", line 382, in <lambda>
    return lambda: format_prompt(tpl)
  File "doitlive.py", line 377, in format_prompt
    raise ConfigurationError('Invalid variable in prompt template.')
__main__.ConfigurationError: Invalid variable in prompt template.
```

**Comment by sloria** [comment]
Ha, well that answers that question. Should be easy to fix that specific issue, but that can happen outside of your PR.
